insert into tb_brand (brand, description, gender) values ('Nike','TÊNIS AIR JORDAN 3 RETRO MASCULINO', 'masculino')
insert into tb_brand (brand, description, gender) values ('Nike', 'TÊNIS NIKE AIR FORCE 1 PIXEL FEMININO', 'feminino')
insert into tb_brand (brand, description, gender) values ('Vans', 'TENIS VANS OLD SKOOL', '')
insert into tb_brand (brand, description, gender) values ('Puma', 'TÊNIS PUMA SUEDE CLASSIC', 'masculino')
insert into tb_brand (brand, description, gender) values ('Adidas', 'TÊNIS ADIDAS SUPERSTAR FEMININO', 'feminino')
insert into tb_brand (brand, description, gender) values ('Adidas', 'TÊNIS ADIDAS SUPERSTAR MASCULINO', 'masculino')
insert into tb_brand (brand, description, gender) values ('Puma', 'TÊNIS PUMA SUEDE CLASSIC XXI MASCULINO', 'masculino')
insert into tb_brand (brand, description, gender) values ('Puma','TÊNIS PUMA SUEDE STUDS FEMININO', 'feminino')

insert into tb_color (name) values ('preto/branco')
insert into tb_color (name) values ('branco/azul')
insert into tb_color (name) values ('cinza')

insert into tb_brand_color (brand_id, color_id) values (1,1)
insert into tb_brand_color (brand_id, color_id) values (2,1)
insert into tb_brand_color (brand_id, color_id) values (1,2)
insert into tb_brand_color (brand_id, color_id) values (2,3)