insert into tb_brand (brand, delete) values ('Nike', false)
insert into tb_brand (brand, delete) values ('Adidas', false)
insert into tb_brand (brand, delete) values ('Puma', false)
insert into tb_brand (brand, delete) values ('Vans', false)

insert into tb_color (name) values ('preto e branco')
insert into tb_color (name) values ('branco e preto')
insert into tb_color (name) values ('azul')
insert into tb_color (name) values ('azul marinho')
insert into tb_color (name) values ('azul e branco')
insert into tb_color (name) values ('cinza')
insert into tb_color (name) values ('preto e verde')
insert into tb_color (name) values ('branco e verde')

insert into tb_size (size) values (30)
insert into tb_size (size) values (31)
insert into tb_size (size) values (32)
insert into tb_size (size) values (33)
insert into tb_size (size) values (34)
insert into tb_size (size) values (35)
insert into tb_size (size) values (36)
insert into tb_size (size) values (37)
insert into tb_size (size) values (38)
insert into tb_size (size) values (39)
insert into tb_size (size) values (40)
insert into tb_size (size) values (41)
insert into tb_size (size) values (42)
insert into tb_size (size) values (43)
insert into tb_size (size) values (44)
insert into tb_size (size) values (45)
insert into tb_size (size) values (46)


insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS AIR JORDAN 3 RETRO MASCULINO','Esse tenis é mara!', 4.76, 'masculino', false, 287.49, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)
insert into tb_product (product, description, rating, gender, delete, price, brand_id) values ('TÊNIS NIKE AIR MAX 95 FEMININO', 'A marca do swoosh acumula ao longo de décadas muitas cartadas de sucesso dentro e fora do âmbito esportivo, e uma dessas com toda certeza inclui o lendário Tênis Nike Air Max 95. O calçado originalmente foi inspirado na anatomia do corpo humano, criado pelo designer Sergio Lozano, sendo um enorme sucesso na metade de década, onde até mesmo em meio a ascensão dos calçados de basquete, acabou literalmente roubando a cena. Desse modo, esse é um remake com o melhor que a tecnologia atual pode oferecer.', 4.76, 'feminino', false, 599.99, 1)

insert into tb_product_color (product_id, color_id) values (1, 1)
-- insert into tb_product_color (product_id, color_id) values (1, 4)
-- insert into tb_product_color (product_id, color_id) values (2, 2)
-- insert into tb_product_color (product_id, color_id) values (3, 3)
-- insert into tb_product_color (product_id, color_id) values (4, 4)
-- insert into tb_product_color (product_id, color_id) values (5, 5)
-- insert into tb_product_color (product_id, color_id) values (6, 6)
-- insert into tb_product_color (product_id, color_id) values (7, 7)
-- insert into tb_product_color (product_id, color_id) values (8, 8)
-- insert into tb_product_color (product_id, color_id) values (9, 1)
-- insert into tb_product_color (product_id, color_id) values (10, 2)
-- insert into tb_product_color (product_id, color_id) values (11, 3)
-- insert into tb_product_color (product_id, color_id) values (12, 4)
-- insert into tb_product_color (product_id, color_id) values (13, 5)
